# Generated by Django 4.2.20 on 2025-04-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("REFUSED", "Refused"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
