# Generated by Django 4.2.20 on 2025-04-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_appointment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="family_name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
