# Generated by Django 4.2.20 on 2025-04-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_appointment_family_name_appointment_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="family_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
